
#ifndef CSKIN_H
#define CSKIN_H

#include "base/skin.h"

using namespace GUI;


enum CStyleBoxList {

	C_SB_BEGIN=SB_MAX,
	SB_PATTERN_EDITOR_CURSOR,
	SB_ORDERLIST_CURSOR,
	SB_MAIN_STACK_FRAME,
	SB_TOP_STACK_FRAME,
	SB_PLAYBACK_BUTTON_NORMAL,
	SB_PLAYBACK_BUTTON_PRESSED,
	SB_PLAYBACK_BUTTON_HOVER,
	SB_PLAYBACK_BUTTON_FOCUS,
	
	C_SB_MAX
};
	
enum CColorList {

	C_COLOR_BEGIN=SB_MAX,
	COLOR_PATTERN_EDITOR_BG,
	COLOR_PATTERN_EDITOR_ROW_BAR,
	COLOR_PATTERN_EDITOR_ROW_BEAT,
	COLOR_PATTERN_EDITOR_ROW_SUB_BEAT,
	COLOR_PATTERN_EDITOR_NOTE,
	COLOR_PATTERN_EDITOR_NOTE_NOFIT,
	COLOR_PATTERN_EDITOR_NOTE_SELECTED,
	COLOR_PATTERN_EDITOR_HL_BEAT,
	COLOR_PATTERN_EDITOR_HL_BAR,
	COLOR_PATTERN_EDITOR_TRACK_SEPARATOR,
	COLOR_PATTERN_EDITOR_ROW_SEPARATOR,
	COLOR_PATTERN_EDITOR_TRACK_NAME,
	COLOR_PATTERN_EDITOR_AUTOMATION_NAME,
	COLOR_PATTERN_EDITOR_AUTOMATION_VALUE,
	COLOR_PATTERN_EDITOR_AUTOMATION_VALUE_NOFIT,
	COLOR_PATTERN_EDITOR_AUTOMATION_VALUE_SELECTED,
	COLOR_PATTERN_EDITOR_AUTOMATION_POINT,
	COLOR_PATTERN_EDITOR_AUTOMATION_HL_BEAT,
	COLOR_PATTERN_EDITOR_AUTOMATION_HL_BAR,
	COLOR_PATTERN_EDITOR_CURSOR,

	C_COLOR_MAX
	
};

enum CConstantList {

	C_C_BEGIN=C_MAX,
	C_PATTERN_EDITOR_ROW_SEPARATION,
	C_PATTERN_EDITOR_TRACK_SEPARATION,
	C_PATTERN_EDITOR_COLUMN_SEPARATION,
	C_C_MAX
};
	
enum CFontList {

	C_FONT_BEGIN=FONT_MAX,
	FONT_PATTERN_EDITOR,
	FONT_PATTERN_EDITOR_TOP,
	FONT_PATTERN_EDITOR_ROWS,
	FONT_PATTERN_EDITOR_COLUMN_NAME,
	FONT_ORDERLIST,
	FONT_SAMPLETABLE,
	FONT_ENVELOPE,
	C_FONT_MAX
};

enum CTBitmapList {

	C_BITMAP_BEGIN=BITMAP_MAX,
	BITMAP_PATTERN_EDITOR_TRACK_POPUP,
	BITMAP_PATTERN_EDITOR_TRACK_POPUP_PRESSED,

	C_BITMAP_MAX

};


class CSkin  : public Skin {


	virtual void set_default_extra();	
public:
	

	CSkin();
	~CSkin();

};



#endif
